#!/bin/sh /etc/rc.common

START=99

start() {
        if [ $(ps | grep '/etc/wallproxy/startup.py' | grep -v 'grep' | wc -l) -eq 1 ];
        then
                echo WallProxy already running...
                exit 0
        else
        	screen -d -m /etc/wallproxy/startup
        fi
}

stop() {
        kill -9 $(ps |grep '/etc/wallproxy/startup'|grep -v 'grep'|awk '{print$1}')
        screen -wipe
}
